version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask
    image: spielmeister/advancedpythonhw2api:latest
    restart: always
    links:
      - mongo
    ports:
      - "5000:5000"
    depends_on:
      - redis
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: ./models/db
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    image: spielmeister/advancedpythonhw2worker:latest
    depends_on:
      - redis
  redis:
    image: redis